name: "python-deploy"
on:
  deployment:
    types:
      - created

jobs:
   PYTHON_DEPLOY:
    runs-on: self-hosted
    name: login to server
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify on push
        run: |
          pwd
          cd /home/ubuntu/actions-runner/_work/sample-project/sample-project
          ls 
          git pull
          pm2 delete python-deploy
          pm2 start " python3 app.py" --name python-deploy
          sudo apt-get install -y curl
          
          export CHAT_WEBHOOK_URL="https://mail.google.com/chat/u/0/#chat/space/AAAAyHOPgC4"
          curl -X POST -H 'Content-Type: application/json' -d "{'text':'Deployment ,completed.'}" $CHAT_WEBHOOK_URL
      


