name: "python-deploy"
on: 
  push:
    branches:
       - main

jobs:
   PYTHON_DEPLOY:
    runs-on: self-hosted
    name: login to server
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify on push
        run: |
          pwd
          cd /home/ubuntu/actions-runner/_work/sample-project/sample-project
          ls
          pm2 delete python-deploy
          pm2 start "python3 app.py" --name python-deploy
