name: "python-deploy"
on: push

jobs:
  build:
     runs-on: self-hosted
     
     steps:
     - uses: actions/checkout@v3
     - name: set up python
       run: |
        git pull
        ls
        pwd
        cd /home/ubuntu/actions-runner/_work/sample-project/sample-project
        ls
        touch peter
        ls
        pwd
        pm2 start "python3 app.py" --name python-work
