name: "python-deploy"
on: push

jobs:
   PYTHON_DEPLOY:
    runs-on: self-hosted
    name: login to server
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Notify on push
        run: |
          pwd
          git pull
          cd /home/ubuntu/actions-runner/_work/sample-project/sample-project
          pm2 start " python3 app.py" --name python-deploy
