name: "Notification And shell Script From Variable"
on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: self-hosted
    steps:
    - name: Sample Setup
      run: |
        ls
        pwd
         echo "Satge Env ${{ vars.ENV }} "
