name: "Notification And shell Script From Variable"
on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: self-hosted
    steps:
    - name: Sapmle Setup
      run: |
        ls
        pwd
         
