name: "Notification And shell Script From Variable"
on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: self-hosted
    steps:
    - name: Sample Setup
      run: |
        pwd
         echo "Satge Env ${{ vars.stage.ENV }} "
         echo "command ${{ vars.NOTIFICATION }}" >> comand.sh 
         ls
         cat comand.sh
         bash comand.sh
